LF-1011-1 arm64: dts: imx8mm-evk-inmate: fix build break
commit e3be6fec0c0a64b3ab3ef3c3a1c3d18edea550e4 from
https://source.codeaurora.org/external/imx/linux-imx

Remove memory node deletion due to below change:
e1437b09449a ("arm64: dts: imx8mm: Memory node should be in board DT")

Otherwise,met below error:
Error: ../arch/arm64/boot/dts/freescale/imx8mm-evk-inmate.dts:69.15-34 Label or path /memory@40000000 not found
FATAL ERROR: Syntax error parsing input tree
  DTC     arch/arm64/boot/dts/freescale/imx8mm-ddr4-evk-revb-rm67191.dtb
scripts/Makefile.lib:302: recipe for target 'arch/arm64/boot/dts/freescale/imx8mm-evk-inmate.dtb' failed

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>