MLK-23547: ASoC: SOF: Use machine_drv_name on OF platforms
commit 23f598fa9016edfcd17bb3c723c35e2a77ebad0b from
https://source.codeaurora.org/external/imx/linux-imx

On OF platforms information about machine driver is stored
in sof_pdata->machine_drv_name.

Without this SOF probe fails with:
error: no matching ASoC machine driver found - aborting probe

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>