LF-1011-23 gpu: drm: bridge: dsim: update using of drm_panel_get_modes
commit fe1275d36ad1f5ea4b0d66a10318d56d6b74e99c from
https://source.codeaurora.org/external/imx/linux-imx

API changed since:
0ce8ddd8e06d ("drm/panel: add drm_connector argument to get_modes()")

../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_connector_get_modes’:
../drivers/gpu/drm/bridge/sec-dsim.c:1798:9: error: too few arguments to function ‘drm_panel_get_modes’
 1798 |  return drm_panel_get_modes(dsim->panel);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>