LF-4185 media: mxc_capture: Fix VTE test failure due to accumulated error
commit b0519c4b9531e65e71b3ff5db18553d6ad840099 from
https://source.codeaurora.org/external/imx/linux-imx

$ v4l_capture_testapp -T 10

...
camera_module are: ov5640_camera_int ov5640_camera_mipi_v2
OK to setup v4l
v4l_capture_testapp    0  TINFO  :  Testing if v4l_capture_testapp test case is OK
v4l_capture_testapp    0  TINFO  :  capture mode is 0

v4l_capture_testapp    0  TINFO  :  Default image: left = 0, top = 0, width = 320, height = 240
v4l_capture_testapp    0  TINFO  :  VIDIOC_S_FBUF executed - overlay type OVERLAY is set
v4l_capture_testapp    0  TINFO  :  Please wait 10 sec ...

v4l_capture_testapp    0  TINFO  :  Start capturing...
[   54.864917] fb_set_var err code -1
v4l_capture_testapp    0  TWARN  :  v4l_capture_test.c:871: Error stop_capturing() for VIDIOC_OVERLAY : Operation not permitted
v4l_capture_testapp    1  TBROK  :  v4l_capture_test.c:1872: /dev/video0 capturing stop failed
v4l_capture_testapp    2  TFAIL  :  v4l_capture_main.c:537: v4l_capture_testapp test case did NOT work as expected
...

the root cause is that following patch accumulates the error when function returns.

4e66a87f64f2 LF-2488 media: mxc_capture: Fix Coverity Issue:11024996 Unchecked return value

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Reviewed-by: G.n. Zhou <guoniu.zhou@nxp.com>
(cherry picked from commit f12192aaaf37d43ae41cbdaba6aab4a8f5024312)
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>