MLK-21876-10 gpu: drm: dpu: fix headfile reference issue (part 1)
commit fc306721807e912302c8052ff35f6c0c28897fb1 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>