MGS-4530-2 disable busfreq-imx to fix L4.19 dash build
commit 322374dcdcc2a6026102e0f0167ab7f30fe99fed from
https://source.codeaurora.org/external/imx/linux-imx

gc_hal_kernel_platform_imx.c:90:14: fatal error: linux/busfreq-imx.h: No such file or directory
 #    include <linux/busfreq-imx.h>

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>