firmware: imx: fix build error on arm32 platforms
commit fecd20bf6dfde4bfc5ec2b185e5b8f0d5a6e6616 from
https://source.codeaurora.org/external/imx/linux-imx

Moving SCU macro definition out of CONFIG_IMX_SCU in case they may be
used on ARM32 platforms.

Fix the following build error with imx_v7_defconfig.
../drivers/remoteproc/imx_rproc.c: In function ‘imx_rproc_detect_mode’:
../drivers/remoteproc/imx_rproc.c:1077:35: error: ‘IMX_SC_IRQ_GROUP_REBOOTED’ undeclared (first use in this function)
 1077 |    ret = imx_scu_irq_group_enable(IMX_SC_IRQ_GROUP_REBOOTED,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/remoteproc/imx_rproc.c:1077:35: note: each undeclared identifier is reported only once for each function it appears in
  CC      drivers/iio/industrialio-trigger.o

Cc: Ranjani Vaidyanathan <ranjani.vaidyanathan@nxp.com>
Fixes: b642cbd32811 ("MLK-25649-1 firmware: imx: imx-scu-irq: Add support for identifying SCU wakeup source from sysfs")
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>