LF-1162-5: clk: imx: imx8mm: add back required clk.h headfile
commit f6d5789900d75c3bf32d1e4904ff84c5ba797e97 from
https://source.codeaurora.org/external/imx/linux-imx

Otherwise meet below build break:
../drivers/clk/imx/clk-imx8mn.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mn.c:306:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  306 |   ret = clk_prepare_enable(clks[array[i]]->clk);
      |         ^~~~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>